# Starter pipeline
- task: UiPathPack@4
  inputs:
    versionType: 'CurrentVersion'
    projectJsonPath: 'project.json'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
# Start with a minimal pipeline that you can customize to build and deploy your code.
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    outputType: 'Process'
    splitOutput: false
    enablePackageMetadata: true
    repositoryUrl: 'https://github.com/MADHU1419/TestCI-CD'
    repositoryType: 'Git'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
